- name: variables from files
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: print variables
    ansible.builtin.debug
     msg: "we are learning: {{NAME}}, duration is: {{DURATION}}"